services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: production
    environment:
      - NODE_ENV=staging
      - HOST=0.0.0.0
    env_file:
      - server/.env.staging
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
